---
version: "3.8"

services:
  cache:
    image: varnish:7.3-alpine
    restart: always
    environment:
      - VARNISH_SIZE=10240M
    depends_on:
      - api
    ports:
      - '80:80'
    container_name: cache
    volumes:
      - ./files/default.vcl:/etc/varnish/default.vcl
  api:
    hostname: api
    build: api
    restart: always
    ports:
      - 8080
